[versions]
agp = "8.10.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
cardview = "1.0.0"
firebaseFirestore = "25.1.4"
googleServices = "4.4.2"
firebaseBom = "33.13.0"
firebaseAnalytics = "22.4.0"
volley = "1.2.1"

loggingInterceptor = "5.0.0-alpha.14"
recyclerview = "1.4.0"
gson = "2.13.1"
okhttp = "5.0.0-alpha.14"
firebaseAuth = "23.2.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
google-services = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebaseAnalytics" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

glide = "com.github.bumptech.glide:glide:5.0.0-rc01"
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
